import { renderIcon } from '@/utils/index';
import {
  DashboardOutlined,
  HomeOutlined,
  SecurityScanOutlined,
  UserOutlined,
  SettingOutlined,
  ProfileOutlined,
  ShoppingCartOutlined,
  MenuOutlined,
  ApiOutlined,
  ControlOutlined,
  CodeSandboxOutlined,
  CalculatorOutlined,
  CarOutlined,
  ProjectOutlined,
  AppstoreOutlined,
  WalletOutlined,
  DollarCircleOutlined,
  CodepenOutlined,
  GoldOutlined,
  AlertOutlined,
} from '@vicons/antd';

//Front-end routing icon mapping table
export const constantRouterIcon = {
  DashboardOutlined: renderIcon(DashboardOutlined),
  HomeOutlined: renderIcon(HomeOutlined),
  SecurityScanOutlined: renderIcon(SecurityScanOutlined),
  UserOutlined: renderIcon(UserOutlined),
  SettingOutlined: renderIcon(SettingOutlined),
  ProfileOutlined: renderIcon(ProfileOutlined),
  ShoppingCartOutlined: renderIcon(ShoppingCartOutlined),
  MenuOutlined: renderIcon(MenuOutlined),
  CarOutlined: renderIcon(CarOutlined),
  CodeSandboxOutlined: renderIcon(CodeSandboxOutlined),
  CalculatorOutlined: renderIcon(CalculatorOutlined),
  ApiOutlined: renderIcon(ApiOutlined),
  ControlOutlined: renderIcon(ControlOutlined),
  ProjectOutlined: renderIcon(ProjectOutlined),
  AppstoreOutlined: renderIcon(AppstoreOutlined),
  WalletOutlined: renderIcon(WalletOutlined),
  DollarCircleOutlined: renderIcon(DollarCircleOutlined),
  CodepenOutlined: renderIcon(CodepenOutlined),
  GoldOutlined: renderIcon(GoldOutlined),
  AlertOutlined: renderIcon(AlertOutlined),
};
